### ISSUE TITLE
Not an issue but a SUCCESS!

### ISSUE THREAD

**Issue by wr3cckl3ss1** [0xkol/badspin#3]
GitHub doesn't have a congratulations or great work tab. So forgive me for posting here. Keep up the good work.

![Screenshot from 2023-05-24 07-36-55.png](https://github.com/0xkol/badspin/assets/97212092/cbb60b72-b674-4960-a522-c092fc0adb6b)

S22 Ultra on AVHF

![IMG_20230524_131033_100.jpg](https://github.com/0xkol/badspin/assets/97212092/f9384d6c-0f56-405c-bb59-f542d4957661)

S22 Ultra on AVF1.

**Comment by 0xkol** [comment]
Glad to hear that!
